name: CI PIPELINE

on: 
   push:

jobs:
    build:
        runs-on: ubuntu-latest

        environment: 
          name: Production
    
        steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: 3.11
        
        - name: Set up CML
          uses: iterative/setup-cml@v2

        - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        
        - name: Run Main file
          run: | 
            python main.py
        
        - name: Create report
          env:
            REPO_TOKEN: ${{ secrets.SuperSecret }}
          run: |
            echo "# First line of our report" >> report.md
            echo "printed the contents of the main.py file" >> report.md
            
            cml comment create report.md